```mermaid
classDiagram
    class App
    App --> TimerFormComponent
    App --> HistoryComponent

    class TimerService
    TimerService --> HistoryService
    TimerService --> NotificationService

    HistoryService <.. HistoryComponent
    TimerService <.. TimerFormComponent
    TimerService <.. HistoryComponent
```
